site_name: dtt
theme: readthedocs
nav:
    - Home: 'index.md'
    - 'Level of detail':
        - 'Highlevel..': 'highlevel/index.md'
        - 'Detailed..': 'detailed/index.md'
        - 'Reeel deep':
            'Beyond funny...': 'beyondfunny/index.md'
    - About: 'about/md.md'
    
