site_name: dtt
theme: readthedocs
nav:
    - Home: 'index.md'
    'User Guide':
        - 'Highlevel..': 'Highlevel/index.md'
        - 'Detailed..': 'detailed/index.md'
    - About: 'about/md.md'
    
